// <auto-generated />
namespace MarketPlace.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class m13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m13));
        
        string IMigrationMetadata.Id
        {
            get { return "201310222351065_m13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
