// <auto-generated />
namespace MarketPlace.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class m10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m10));
        
        string IMigrationMetadata.Id
        {
            get { return "201310222256299_m10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
